import type { RequestHandler } from '@sveltejs/kit'
import { handle } from './_middleware'

const characters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

/**
 * Return a seed to the frontend so the server and frontend can generate the same random numbers
 * This keeps the numbers generated by SSR and the client the same
 * https://stackoverflow.com/questions/70714461/sveltekit-rendering-a-random-prop-is-different-between-server-and-client/70776238
 */
export const get: RequestHandler = handle()(async () => {
    let letters = Array(8)
    for (let i = 0; i < letters.length; ++i) {
        letters[i] = characters[Math.floor(Math.random() * characters.length)]
    }

    return {
        body: {
            seed: letters.join(''),
        },
    }
})
