import type { RequestHandler } from '@sveltejs/kit'
import { handle } from './_middleware'

/**
 * Just returns a lot of random numbers for the frontend to use
 * This keeps the numbers generated by SSR and the client the same
 * https://stackoverflow.com/questions/70714461/sveltekit-rendering-a-random-prop-is-different-between-server-and-client/70776238
 */
export const get: RequestHandler = handle()(async () => {
    const numbers = Array(1000)
    for (let i = 0; i < numbers.length; ++i) {
        numbers[i] = Math.random()
    }

    return {
        body: {
            items: numbers,
        },
    }
})