import type { RequestHandler } from '@sveltejs/kit'
import { handle } from './_middleware'
import * as random from '$lib/shared/random'

/**
 * Return a seed to the frontend so the server and frontend can generate the same random numbers
 * This keeps the numbers generated by SSR and the client the same
 * https://stackoverflow.com/questions/70714461/sveltekit-rendering-a-random-prop-is-different-between-server-and-client/70776238
 */
export const get: RequestHandler = handle()(async () => {
    return {
        body: {
            seed: random.string(),
        },
    }
})
